<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNAydrod\FunctionalTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNAydrod/FunctionalTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNAydrod.legacy');

    return;
}

if (!\class_exists(FunctionalTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNAydrod\FunctionalTestDebugProjectContainer::class, FunctionalTestDebugProjectContainer::class, false);
}

return new \ContainerNAydrod\FunctionalTestDebugProjectContainer();
